# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4638126eb51213411c310e85443bde801a6de9f7fc09ebacd2f9a7c2f11d20273846c1f9180e097a1ea1862cb501d97918ee2a275fbc8b6476066f797d456611

test:
  secret_key_base: 897139908b0d771e5e088468eb8d9542895cdf2f0f793f482b4234cf0fa2f4b927dd241af2d9bdca4429eae5d52043cf1e289ca9a499763b1af9470a110e4396

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
